org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# برای اینکه بیلد ریلیز با R8 کوچک شود ولی نمادهای فلاتر حفظ شوند
android.enableR8.fullMode=false
# سازگاری با پلاگین فلاتر (local.properties توسط flutter tool ساخته می‌شود)
